apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret

type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.app.SPRING_DATASOURCE_USERNAME | default "" }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.app.SPRING_DATASOURCE_PASSWORD | default "" }}