apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret

type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.app.POSTGRES_USER | default "" }}
  POSTGRES_PASSWORD: {{ .Values.secrets.app.POSTGRES_PASSWORD | default "" }}